global:
  scrape_interval: 60s # By default, scrape targets every 15 seconds.
  scrape_timeout: 50s
    
rule_files:
  - "rules.yml"
  - "alert.rules"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 60s

    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'node-exporter'
    scrape_interval: 60s
    metrics_path: /metrics
    file_sd_configs:
      - files:
          - targets-node-exporter.json

  - job_name: 'cadvisor-exporter'
    scrape_interval: 60s
    static_configs:
      - targets: ['localhost:8080']

